[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'cd alt-tag-generator && npm install',
    'cd alt-tag-generator && npm run build'
]

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1'
